# Generated by Django 4.2.4 on 2023-08-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='section',
            new_name='section_id',
        ),
    ]
