# Generated by Django 4.2.4 on 2023-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_alter_subject_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Dob',
            new_name='dob',
        ),
        migrations.AlterField(
            model_name='staff',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
