# Generated by Django 4.2.4 on 2023-09-04 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0016_staff_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='date_end',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
