# Generated by Django 4.2.4 on 2023-09-04 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0017_staff_leave_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='day',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
