# Generated by Django 4.2.4 on 2023-09-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0018_staff_leave_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
