# Generated by Django 4.2.4 on 2023-09-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDmand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('old_district', models.CharField(max_length=100)),
                ('old_municipilaty', models.CharField(max_length=200)),
                ('old_word_no', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=100)),
                ('municipilaty', models.CharField(max_length=200)),
                ('word_no', models.CharField(max_length=2)),
                ('greand_father', models.CharField(max_length=150)),
                ('father_husband', models.CharField(max_length=150)),
                ('citizenship_no', models.CharField(max_length=150)),
                ('issue_place', models.CharField(max_length=150)),
                ('isssue_date', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('loan_amount', models.CharField(max_length=7)),
                ('loan_text', models.CharField(max_length=300)),
                ('maturity_age', models.CharField(max_length=50)),
            ],
        ),
    ]
