# Generated by Django 4.2.4 on 2023-09-05 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandmand',
            name='propose',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
