# Generated by Django 4.2.4 on 2023-09-05 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_demand', '0003_loandmand_country_loandmand_old_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandmand',
            name='province',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandmand',
            name='zone',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
