# Generated by Django 4.2.4 on 2023-09-05 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_demand', '0004_loandmand_province_loandmand_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandmand',
            name='loan_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
