# Generated by Django 4.2.4 on 2023-09-05 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_demand', '0005_loandmand_loan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandmand',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/document'),
            preserve_default=False,
        ),
    ]
