# Generated by Django 4.2.4 on 2023-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_demand', '0006_loandmand_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandmand',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
